spring:
  profiles:
    active: dev
  jackson:
    serialization:
      write_dates_as_timestamps: true

  servlet:
    multipart:
      max-file-size: 10MB

  jdbc:
    template:
      query-timeout: 15

  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/gis-test
    #这里使用的驱动不一样！，可以自动添加gis的各种类型
    driver-class-name: com.github.lonelyleaf.gis.db.jts.JtsGisWrapper
    #url也不一样
    url: jdbc:postgresql_JTS://localhost:5432/gis-test
    username: postgres
    password: admin
    initialization-mode: never


mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: "com.github.lonelyleaf.gis.mybatis.jts"