spring:
  profiles:
    active: dev
  jackson:
    serialization:
      write_dates_as_timestamps: true

  servlet:
    multipart:
      max-file-size: 10MB

  jdbc:
    template:
      query-timeout: 15

  flyway:
    enabled: true

  datasource:
#        driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://localhost:5432/gis-test
    #这里使用的驱动不一样！，可以自动添加jts的各种类型
    driver-class-name: org.postgis.jts.JtsWrapper
    #url也不一样
    url: jdbc:postgres_jts://localhost:5432/jts-test
    username: postgres
    password: admin
    initialization-mode: never

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: "com.github.lonelyleaf.gis.mybatis.jts"